name: narrative-nlp-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - nltk
  - gensim
  - scikit-learn
  - pytest
  - black
  - pytorch>=1.2.0,!=1.3.0 # torch in pip allennlp https://github.com/allenai/allennlp/blob/master/setup.py
  - jsonnet>=0.10.0
  - overrides==2.8.0
  - spacy >=2.1.0,<2.3
  - tensorboardX>=1.2
  - boto3
  - requests>=2.18
  - tqdm>=4.19
  - h5py
  - scipy
  - flaky
  - responses>=0.7
  - conllu==2.2.2
  - jsonpickle
  - pip
  - pip:
      - allennlp
