name: narrative-nlp-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - jupyterlab
  - nbconvert
  - nltk
  - cython
  - gensim
  - scikit-learn
  - pytest
  - black
  - pip
  - pip:
      - allennlp
