name: narrative-nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - ipyparallel
  - jupyter
  - pandas
  - nltk
  - gensim
  - scikit-learn
  - pytorch # pytorch is needed by allennlp and from pip not working on macOS
  - pip
  - pip:
      - allennlp
      - tensorflow
      - tensorflow-hub
