name: narrative-nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - ipyparallel
  - jupyterlab
  - pandas
  - nltk
  - gensim
  - scikit-learn
  - pytorch # pytorch is needed by allennlp and from pip not working on macOS
  - allennlp
  - tensorflow>=2
  - tensorflow-hub
